/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg321_project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Sierra Laney
 */
public class GamePlayFrame extends javax.swing.JFrame {

    Storyline storyline = new Storyline();
    boolean checkpoint = false;

    /**
     * Creates new form NewJFrame
     */
    public GamePlayFrame() {
        initComponents();
        StoryTextArea.setLineWrap(true);
        StoryTextArea.setText(storyline.tree.current.story);
    }

    public GamePlayFrame(Node cont) {
        initComponents();
        StoryTextArea.setLineWrap(true);
        storyline.tree.current = cont;
        StoryTextArea.setText(storyline.tree.current.story);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StoryTextArea = new javax.swing.JTextArea();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonA.setBackground(new java.awt.Color(78, 59, 56));
        jButtonA.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jButtonA.setForeground(new java.awt.Color(213, 204, 193));
        jButtonA.setText("A");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonA);
        jButtonA.setBounds(170, 240, 50, 40);

        jButtonB.setBackground(new java.awt.Color(78, 59, 56));
        jButtonB.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jButtonB.setForeground(new java.awt.Color(213, 204, 193));
        jButtonB.setText("B");
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonB);
        jButtonB.setBounds(349, 240, 50, 40);

        jScrollPane1.setForeground(new java.awt.Color(78, 59, 56));

        StoryTextArea.setColumns(20);
        StoryTextArea.setFont(new java.awt.Font("Baskerville Old Face", 0, 13)); // NOI18N
        StoryTextArea.setForeground(new java.awt.Color(78, 59, 56));
        StoryTextArea.setRows(5);
        jScrollPane1.setViewportView(StoryTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 40, 450, 170);

        BackgroundImage.setBackground(new java.awt.Color(0, 0, 0));
        BackgroundImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carden Roden\\Documents\\College\\Senior Year (1st and 2nd)\\1st Semester\\CS 321\\Background_CS_321.JPEG2.jpg"));
        getContentPane().add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 580, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        Node new_node_a = storyline.tree.current;
        update_text_a(StoryTextArea, new_node_a);
        storyline.tree.current = storyline.tree.current.left;
        update_background(BackgroundImage);
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        Node new_node_b = storyline.tree.current;
        update_text_b(StoryTextArea, new_node_b);
        storyline.tree.current = storyline.tree.current.right;
        update_background(BackgroundImage);
    }//GEN-LAST:event_jButtonBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlayFrame().setVisible(true);
            }
        });
    }

    public void update_text_a(JTextArea a, Node n) {
        Node current;
        current = n;
        a.setText(current.left.story);
    }

    public void update_text_b(JTextArea a, Node n) {
        Node current;
        current = n;
        a.setText(current.right.story);
    }
    
    public void update_background(JLabel b) {
        
        if (storyline.tree.current == storyline.tree.current.right ||
            storyline.tree.current == storyline.tree.current.left.right.right ||
            storyline.tree.current == storyline.tree.current.left.right.left.right ||
            storyline.tree.current == storyline.tree.current.left.right.left.left ||
            storyline.tree.current == storyline.tree.current.left.left.left) {
            
            b.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carden Roden\\Documents\\College\\Senior Year (1st and 2nd)\\1st Semester\\CS 321\\Fail_CS_321.JPEG2.jpg")); // NOI18N
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JTextArea StoryTextArea;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
