package pkg321_project;



/**
 *
 * @author Sierra Laney
 */
public class IntroductionFrame extends javax.swing.JFrame {
Storyline storyline = new Storyline();

    /**
     * Creates new form IntroductionFrame
     */
    public IntroductionFrame() {
        initComponents();
        
        gameTitle.setBackground(new java.awt.Color(0,0,0,1));
        instructions.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGameButton = new javax.swing.JButton();
        ContinueButton = new javax.swing.JButton();
        gameTitle = new javax.swing.JTextField();
        instructions = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NewGameButton.setBackground(new java.awt.Color(78, 59, 56));
        NewGameButton.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        NewGameButton.setForeground(new java.awt.Color(213, 204, 193));
        NewGameButton.setText("New Game");
        NewGameButton.setFocusable(false);
        NewGameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NewGameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewGameButton);
        NewGameButton.setBounds(120, 240, 100, 23);

        ContinueButton.setBackground(new java.awt.Color(78, 59, 56));
        ContinueButton.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(213, 204, 193));
        ContinueButton.setText("Continue");
        ContinueButton.setMaximumSize(new java.awt.Dimension(83, 23));
        ContinueButton.setMinimumSize(new java.awt.Dimension(83, 23));
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ContinueButton);
        ContinueButton.setBounds(250, 240, 100, 23);

        gameTitle.setEditable(false);
        gameTitle.setBackground(new java.awt.Color(255, 255, 255));
        gameTitle.setFont(new java.awt.Font("Baskerville BT", 0, 24)); // NOI18N
        gameTitle.setForeground(new java.awt.Color(213, 204, 193));
        gameTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gameTitle.setText("Game Title");
        gameTitle.setBorder(null);
        gameTitle.setCaretColor(new java.awt.Color(213, 204, 0));
        gameTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameTitleActionPerformed(evt);
            }
        });
        getContentPane().add(gameTitle);
        gameTitle.setBounds(170, 40, 130, 30);

        instructions.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        instructions.setForeground(new java.awt.Color(213, 204, 193));
        instructions.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        instructions.setText("instructions");
        instructions.setBorder(null);
        getContentPane().add(instructions);
        instructions.setBounds(120, 80, 230, 150);

        backgroundImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carden Roden\\Documents\\College\\Senior Year (1st and 2nd)\\1st Semester\\CS 321\\Background_CS_321.JPEG2.jpg")); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 500, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        this.setVisible(false);
        new GamePlayFrame(storyline.tree.current.left.left).setVisible(true);
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameButtonActionPerformed
        this.setVisible(false);
        new GamePlayFrame().setVisible(true);
    }//GEN-LAST:event_NewGameButtonActionPerformed

    private void gameTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroductionFrame().setVisible(true);
            }
        });
    }
    
    public void continue_game () {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueButton;
    private javax.swing.JButton NewGameButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTextField gameTitle;
    private javax.swing.JTextField instructions;
    // End of variables declaration//GEN-END:variables
}
